"""Markdown report generation (human-readable, same data as JSON)."""

from __future__ import annotations

from .models import ValidationReport


def to_markdown(report: ValidationReport) -> str:
    """Generate a clean Markdown report."""
    m = report.metadata
    s = report.scores

    lines = [
        f"# Magnus Validator Report v{m.version}",
        "",
        f"**Timestamp:** {m.timestamp}",
        f"**Seed:** `{m.seed}`",
        f"**Model:** {m.model}",
        "",
        "## Scores",
        "",
        f"- **Recognition**: {s.recognition}/100",
        f"- **Inevitability**: {s.inevitability}/100",
        f"- **Coherence**: {s.coherence}/100",
        f"- **Overall**: **{s.overall}/100**",
        "",
        f"**Interpretation:** {report.interpretation}",
        "",
        f"**Deterministic Hash:** `{report.hash}`",
        "",
        "---",
        "*Generated by Magnus Validator Python port (v1.1-corrected)*",
    ]
    return "\n".join(lines)
